// Frozen pt-BR copy for the admin SPA (Decision 5 in slice 1; same pattern).
// Verbatim from the original Babel-standalone JSX prototype (deleted; see notes/MKT WiFi - Full App.html for historical reference).

export const STR = {
  app: {
    title: "MKT WiFi",
    tagline: "Wi-Fi que paga a conta.",
  },
  login: {
    title: "Entrar",
    sub: "Monetize sua rede captiva com vídeos, capture dados de clientes e gerencie tudo em um só lugar.",
    email: "Email",
    password: "Senha",
    remember: "Manter conectado",
    submit: "Entrar",
    requestAccess: "Solicitar acesso",
    invalid: "Email ou senha incorretos.",
    expired: "Sua sessão expirou. Entre novamente.",
  },
  roles: {
    admin: "Administrador",
    advertiser: "Anunciante",
    viewer: "Visualizador",
  },
  nav: {
    section: { principal: "Principal", operacao: "Operação", configuracao: "Configuração" },
    dashboard: "Início",
    campanhas: "Campanhas",
    usuarios: "Usuários",
    wifi: "Wi-Fi Online",
    conexoes: "Conexões",
    notificacoes: "Notificações",
    relatorios: "Relatórios",
    monetizacao: "Monetização",
    configuracoes: "Configurações",
  },
  topbar: {
    onlineNow: "online agora",
    novaCampanha: "Nova campanha",
    exportar: "Exportar",
    meuPerfil: "Meu perfil",
    sair: "Sair",
  },
  dashboard: {
    title: "Dashboard",
    kpis: {
      reach: "Pessoas atingidas este mês",
      activeCampaigns: "Campanhas ativas",
      investment: "Investimento total",
      onlineDevices: "Dispositivos online agora",
    },
    chart: { title: "Conexões por dia", toggle7d: "7d", toggle30d: "30d" },
    demographics: { title: "Perfil dos usuários", gender: "Gênero", age: "Faixa etária" },
    activeCampaigns: { title: "Campanhas ativas", create: "Criar" },
    liveUsers: { title: "Conectados agora" },
  },
  campanhas: {
    title: "Campanhas",
    view: { cards: "Cards", table: "Tabela" },
    filters: { all: "Todas", active: "Ativas", paused: "Pausadas", ended: "Encerradas" },
    kpi: { total: "Total de campanhas", active: "ativas", views: "Total de visualizações", revenue: "Receita gerada", completion: "Taxa média de conclusão" },
    actions: { edit: "Editar", pause: "Pausar", reactivate: "Reativar", data: "Dados", duplicate: "Duplicar", report: "Relatório", delete: "Excluir" },
    rewardTag: "+30 min acesso",
    statusLabel: { active: "Ativa", paused: "Pausada", ended: "Encerrada" },
    modal: {
      newTitle: "Nova campanha",
      editTitle: "Editar campanha",
      name: "Nome",
      location: "Local / Bairro",
      duration: "Duração (segundos)",
      source: "Origem",
      status: "Status",
      save: "Salvar",
      cancel: "Cancelar",
    },
    toast: { created: "Campanha criada", updated: "Campanha salva", paused: "Campanha pausada", reactivated: "Campanha reativada", duplicated: "Campanha duplicada", deleted: "Campanha removida" },
  },
  usuarios: {
    title: "Usuários",
    search: "Buscar por nome",
    zoneAll: "Todas as zonas",
    zones: ["Centro", "Zona Norte", "Zona Sul", "Zona Leste", "Zona Oeste", "Praia"],
    columns: { name: "Nome", age: "Idade", gender: "Gênero", zone: "Bairro", lastConnection: "Última conexão", connections: "Conexões" },
    kpi: { total: "Total cadastrados", online: "Online agora", avgAge: "Idade média", femPct: "% público feminino" },
    detail: { title: "Detalhes do lead", consent: "Versão do consentimento" },
  },
  wifi: {
    title: "Wi-Fi Online",
    kpi: { online: "Equipamentos online", offline: "Equipamentos offline", connectedUsers: "Dispositivos conectados", bandwidth: "Banda em uso" },
    online: "Online",
    offline: "Sem conexão",
    refresh: "Atualizar",
    cpu: "CPU",
    ram: "RAM",
    users: "usuários",
    up: "↑ Mb/s",
    down: "↓ Mb/s",
    lastSeen: "Última vez visto",
    refreshed: "Dispositivo atualizado",
  },
  conexoes: {
    title: "Conexões",
    fields: {
      title: "Campos coletados pelo portal",
      subtitle: "Imutável por LGPD",
      list: [
        { id: "name", label: "Nome", type: "Texto livre" },
        { id: "age_band", label: "Idade", type: "Faixa etária" },
        { id: "gender", label: "Gênero", type: "Categoria" },
        { id: "neighborhood", label: "Bairro", type: "Lista" },
      ],
    },
    mikrotik: {
      title: "Configuração de rede",
      ip: "IP",
      port: "Porta API",
      user: "Usuário API",
      password: "Senha API",
      session: "Minutos por sessão",
      hotspotActive: "Hotspot ativo",
      redirect: "Redirect",
      sessionLabel: "min/sessão",
      save: "Salvar",
    },
  },
  notificacoes: {
    title: "Notificações",
    rulesTitle: "Regras",
    groupsTitle: "Grupos",
    membersLabel: "membros",
    activeOn: "Ativa",
    activeOff: "Pausada",
  },
  relatorios: {
    title: "Relatórios",
    kpi: { count: "Relatórios", frequency: "Frequência", recipients: "Destinatários", lgpd: "LGPD" },
    columns: { name: "Nome", date: "Data", type: "Tipo", size: "Tamanho" },
  },
  monetizacao: {
    title: "Monetização",
    sub: "Escolha como sua rede é monetizada. Campanhas em andamento mantêm o modelo original.",
    save: "Salvar modelo",
  },
  configuracoes: {
    title: "Configurações",
    empresa: { title: "Empresa", razaoSocial: "Razão social", cnpj: "CNPJ", contactEmail: "Email de contato" },
    integracoes: {
      title: "Integrações",
      whatsapp: "WhatsApp Business API",
      smtp: "SMTP transactional email",
      mikrotik: "MikroTik RouterOS API",
      youtube: "YouTube Data API",
      connected: "● Conectado",
    },
  },
  forbidden: {
    title: "Acesso negado",
    sub: "Você não tem permissão para acessar esta página.",
    cta: "Voltar ao início",
  },
  errors: {
    generic: "Algo deu errado. Tente novamente.",
    network: "Sem conexão com o servidor.",
  },
  emBreve: {
    tooltip: "Em breve — pendente da slice {slice}",
  },
} as const;
